################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/app_freertos.c \
../Core/Src/functions.c \
../Core/Src/gpio.c \
../Core/Src/i2c.c \
../Core/Src/stm32g4xx_hal_msp.c \
../Core/Src/stm32g4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32g4xx.c \
../Core/Src/tim.c \
../Core/Src/usart.c 

CPP_SRCS += \
../Core/Src/main.cpp 

C_DEPS += \
./Core/Src/app_freertos.d \
./Core/Src/functions.d \
./Core/Src/gpio.d \
./Core/Src/i2c.d \
./Core/Src/stm32g4xx_hal_msp.d \
./Core/Src/stm32g4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32g4xx.d \
./Core/Src/tim.d \
./Core/Src/usart.d 

OBJS += \
./Core/Src/app_freertos.o \
./Core/Src/functions.o \
./Core/Src/gpio.o \
./Core/Src/i2c.o \
./Core/Src/main.o \
./Core/Src/stm32g4xx_hal_msp.o \
./Core/Src/stm32g4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32g4xx.o \
./Core/Src/tim.o \
./Core/Src/usart.o 

CPP_DEPS += \
./Core/Src/main.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/app_freertos.o: ../Core/Src/app_freertos.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/app_freertos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/functions.o: ../Core/Src/functions.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/functions.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/gpio.o: ../Core/Src/gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/i2c.o: ../Core/Src/i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32g4xx_hal_msp.o: ../Core/Src/stm32g4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32g4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32g4xx_it.o: ../Core/Src/stm32g4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32g4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32g4xx.o: ../Core/Src/system_stm32g4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32g4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/tim.o: ../Core/Src/tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/usart.o: ../Core/Src/usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/andres/Descargas/Sub_Nucleo/Core" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"/home/andres/Descargas/Sub_Nucleo/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"/home/andres/Descargas/Sub_Nucleo/ros_lib" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

