OBJS += doGitVersion

doGitVersion:
	@touch ./myMainProgram.c
	@echo "#define GIT_VERSION  \"`git describe --abbrev=7 --dirty --always`\"" >  generated_headers/ver_data.h
	@echo "#define COMPILE_DATE  \"`date`\"" >>  generated_headers/ver_data.h
	@echo "#define COMPILE_USER \"`whoami`\"" >> generated_headers/ver_data.h
